# Generated by Django 4.1.2 on 2022-10-16 12:55

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=1)),
                ('image', models.ImageField(upload_to=home.models.image_upload)),
            ],
        ),
    ]
